FROM alpine

ENV USER admin
ENV PASSWD admin

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk update
RUN apk add nginx php php-fpm php-fileinfo php-gd php-json php-curl php-exif php-pdo_sqlite tzdata git apache2-utils --no-cache
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && apk del tzdata
RUN mkdir -p /run/nginx && touch /run/nginx/nginx.pid
RUN sed -i 's/user = nobody/user = nginx/g' /etc/php81/php-fpm.d/www.conf
RUN sed -i 's/group = nobody/group = nginx/g' /etc/php81/php-fpm.d/www.conf
RUN mkdir -p /var/www
RUN mkdir -p /var/www/images
RUN rm -rf /var/cache/apk/*

COPY default.conf /etc/nginx/http.d/default.conf 

WORKDIR /var/www
# 先git clone下
COPY PicUploader /var/www/PicUploader
WORKDIR /var/www
RUN ls -al

RUN chown -R nginx:nginx /var/www/PicUploader \
    && chown -R nginx:nginx /var/www/images \
    && htpasswd -bc /var/www/htpasswd ${USER} ${PASSWD}

WORKDIR /

ADD start.sh /start.sh

RUN chmod +x /start.sh

EXPOSE 80

ENTRYPOINT ["/start.sh"]
